### ISSUE TITLE
jmpress skipping transitions in all presentations on Firefox 31.0

### ISSUE THREAD

**Issue by dc-devs** [jmpressjs/jmpress.js#157]
I just downloaded Firefox 31.0 and noticed that ALL jmpress presentations are skipping from slide to slide with no animation.

Please see my site as well as jmpress's presentations below. 
http://www.displayadtech.com/the_display_advertising_technology_landscape
http://jmpressjs.github.io/jmpress.js/

Am I the only one currently seeing this, could this be a simple configuration setting on my end? jimpress presentations still working as expected in Safari and Chrome. 

Any help pointing in the right direct would be a great help. 

Thanks!

**Comment by freme** [comment]
Thanks, now the animations do work in Chrome and FF

**Comment by matatk** [comment]
I am still experiencing this bug with what I believe is the latest version from npm - 0.4.5.  It seems a PR was accepted to fix this, but it is occurring for me.

I found that the line of code that @DWC01 mentioned above [is now line 91 in jmpress.js](https://github.com/jmpressjs/jmpress.js/blob/gh-pages/dist/jmpress.js#L91) and removing it fixed the problem -- now slide transitions now work in Chrome (49) -- Firefox actually crashes for some reason when I run my presentation, but that was both before and after this edit to the codes I'm not sure that's your problem :-).

Are others seeing the reoccurrence of this bug too?

**Comment by DWC01** [comment]
Hey matatk,

I recently had success using the fix mentioned in the issue below when pulling the latest jmpress version from npm..

https://github.com/jmpressjs/jmpress.js/issues/179
