### ISSUE TITLE
Support for scrollable slides

### ISSUE THREAD

**Issue by JaimeObregon** [jmpressjs/jmpress.js#165]
I love this library, but I'm having a hard time trying to get the **vertical scrollbar to appear and work** when the content inside a slide exceeds its height.

It seems jmpress adds a `overflow: hidden` property to both the `html` and `body`, as well as other wrapper elements. Am I missing something or this means that scrollable slides are not currently supported?

Thank you for this useful library!

**Comment by sokra** [comment]
jmpress doesn't set `overflow` on slides, so you can set it to `auto`.
