### ISSUE TITLE
Consistent code style

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [jmpressjs/jmpress.js#168]
This project's code base does not seems to have a consistent code style.
Since this is a jquery plugin I would suggest to adhere to the [jQuery Core Style Guidelines](http://contribute.jquery.org/style-guide/js/) and enforce it using [grunt jscs plugin](https://github.com/jscs-dev/grunt-jscs)

**Comment by shama** [comment]
Closing because https://github.com/jmpressjs/jmpress.js/pull/171#issuecomment-69217659
